name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ORIGIN: ${{ secrets.ORIGIN }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Make the directory
        run: mkdir -p docs
      - name: Install dependencies
        run: npm install

      - name: Test with Mocha
        run: npm run test:mocha

      - name: Run BBD tests
        run: npm test -- -f html > docs/index.html

      - name: Deploy the app to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          force_orphan: true
